[
<c:forEach items="${foodList}" var="food" varStatus="count">
	{ 
		"id": "${food.id}",
		"description": "${food.description}",
		"unit": "${food.unit}",
		"type": "${food.type}",
		"calories": "${food.calories}",
		"protein": "${food.protein}",
		"lipids": "${food.lipids}",
		"carbohydrate": "${food.carbohydrate}",
		"fibre": "${food.fibre}",
		"calcium": "${food.calcium}",
		"magnesium": "${food.magnesium}",
		"manganese": "${food.manganese}",
		"phosphorus": "${food.phosphorus}",
		"iron": "${food.iron}",
		"sodium": "${food.sodium}",
		"additionOfSodium": "${food.additionOfSodium}",
		"potassium": "${food.potassium}",
		"copper": "${food.copper}",
		"zinc": "${food.zinc}",
		"selenium": "${food.selenium}",
		"retinol": "${food.retinol}",
		"a": "${food.a}",
		"b1": "${food.b1}",
		"b2": "${food.b2}",
		"b3": "${food.b3}",
		"equivalentB3": "${food.equivalentB3}",
		"b6": "${food.b6}",
		"b12": "${food.b12}",
		"folate": "${food.folate}",
		"d": "${food.d}",
		"e": "${food.e}",
		"c": "${food.c}",
		"cholesterol": "${food.cholesterol}",
		"satturedFattyAcid": "${food.satturedFattyAcid}",
		"monounsaturatedFattyAcids": "${food.monounsaturatedFattyAcids}",
		"polyunsaturatedFattyAcids": "${food.polyunsaturatedFattyAcids}",
		"linoleic": "${food.linoleic}",
		"linolenic": "${food.linolenic}",
		"transFattyAcidTotal": "${food.transFattyAcidTotal}",
		"sugar": "${food.sugar}",
		"additionSugar": "${food.additionSugar}"
	}${count.last ? "" : ","}
</c:forEach>
]
